# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

configfile: "config.yaml"

rule all:
  input:
    expand("result/{samples}/{samples}_{readpair}.count", samples=config["samples"], readpair=config["read_pairs"])

rule count_reads:
  input: "{sample}_{readpair}.fastq"
  output: "result/{sample}/{sample}_{readpair}.count"
  params: sample= "{sample}", rp="{readpair}"
  shell:
    """
echo "sample: {params.sample}" > {output}
echo "readpair: {params.rp}" >> {output}
wc {input} >> {output}     
    """

