# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

configfile: "config.yaml"

include: "rules/rand_gen.rule"
include: "rules/sum_value.rule"

rule all:
  input:
    expand("analysis/processed_{rand_counts}.random", rand_counts=config["rand_count"])
