# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

rule example:
  input:
    A = "file1",
    B = "file2"
  output: "out1"
  run:
    for i in input:
      print("doing stuff on input: %s" % i)

    print("input files are: %s" % input)

    shell("touch {output}")
